### ISSUE TITLE
Subscribe Button Fixation

### ISSUE THREAD

**Issue by BowlPulp** [Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service#13]
Fixing "Subscribe Button" in the website, currently it just redirects on top of website.

https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/67683793/0396f6a4-7bde-4f4e-9d04-0f80dbc34097

Solutions - 
Possibly creating a googlesheet db where it will store the emails added.

**Comment by KartikeyBartwal** [comment]
Looks good! Its an important issue

**Comment by priyamaggarwal18** [comment]
Yes @BowlPulp , Go for it.

**Comment by BowlPulp** [comment]
Done! 
https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/pull/14
