### ISSUE TITLE
Contact Us Working

### ISSUE THREAD

**Issue by BowlPulp** [Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service#16]
"Contact Us" is currently just accepting values and not storing them anywhere, so I have a solution for that. Kindly allow me to work on this issue.

https://github.com/Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service/assets/67683793/9faa8ff8-87b4-4b99-87a3-b7be6864c3f4

Solution: Storing them in google form/sheets.

**Comment by priyamaggarwal18** [comment]
@BowlPulp we are done with Hacktoberfest 2023.
