### ISSUE TITLE
Add a Login/signup form.

### ISSUE THREAD

**Issue by priyamaggarwal18** [Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service#2]

**Comment by awsmdeep** [comment]
hi @priyamaggarwal18 i hope you are doing well , can you assign me this work

**Comment by Abishkardhenga** [comment]
hey @priyamaggarwal18  I am interested in this topic if You assigned it to me . I will go forward .

**Comment by priyamaggarwal18** [comment]
@awsmdeep    I am assigning this issue to you.
