### ISSUE TITLE
enhance readme

### ISSUE THREAD

**Issue by pinak22dhir** [Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service#4]
@priyamaggarwal18  you can also add code of conduct like this:

**Comment by cmhandan** [comment]
I am intrested to this issue please do assign me ,

**Comment by priyamaggarwal18** [comment]
@Chandan-Kumar-Mahato what will you add?

**Comment by cmhandan** [comment]
I can add the code of conduct while anyone is contributing to this project , as in the readme section you have only mention how o contribute but not how to maintain the code and conduct while contributing.

**Comment by priyamaggarwal18** [comment]
okay go for it.

**Comment by cmhandan** [comment]
I have got one question here shall i add the code of conduct to the readme file or maintain the separate file of it ?

**Comment by priyamaggarwal18** [comment]
add in readme only
