### ISSUE TITLE
add more content to footer.

### ISSUE THREAD

**Issue by priyamaggarwal18** [Open-Source-Chandigarh/U-Move-Scan-to-Ride-Service#8]

**Comment by harshvyas-22** [comment]
i would love to contribute please assign to me

**Comment by KartikeyBartwal** [comment]
I'm on it

**Comment by KartikeyBartwal** [comment]
please specify what are you referring by footer ? The footer tag is empty. By any chance are you referring 'Contact Us' ?
If you are referring to the first one, please specify what all things do you want in the footer

**Comment by harshvyas-22** [comment]
i have completed it in Pr #9
